### ISSUE TITLE
Units and dimensions

### ISSUE THREAD

**Issue by jlstevens** [CubeBrowser/cube-explorer#35]
HoloViews currently allows you to declare `Dimension` objects with specified units where the `unit` argument is a text string e.g `'Celsius'` which can then used in axis labels and titles appropriately.

Currently, a dimension can be specified as a string, which results in the automatic creation of a `Dimension` object with the given name or you can construct a `Dimension` explicitly. Although the latter approach is more flexible, it can become repetitive when the same dimensions is used over and over in a notebook. For this reason, it is recommended that often used dimensions are declared once (e.g at the top of a notebook) so that they can be easily reused.

There might be an an even more convenient approach which would be to define a small 'library' of `Dimension` presets. These dimensions could have standardized names, units and ranges which could also help people stick to a sensible convention.

For instance, you could define something like `hv.Image(data, vdims=[hv.dims.hPa]` where `hv.dims` would be a tab-completable library of possible dimensions. In this example, the corresponding dimension would have a standardized name (say `'Pressure'`), associated units ( `'hPa`) and declared hard ranges (ensuring the value is positive) and an optional soft ranges (i.e a range that is generally suitable but not strict).

Defining dimensions this way might help with issue #34 as an alternative to declaring dimension ranges on cubes themselves. If the ranges on cubes can generally be specified with an appropriate dimension preset this might be an easier approach. For instance, dimensions such as latitude and longitude (and others) might have standard, bounded ranges that can easily be reused.

This suggestion would need to be considered as part of more extensive unit support in HoloViews including unit conversions and general unit awareness (see ioam/holoviews#21).

**Comment by philippjfr** [comment]
I'll expand on this a little bit and offer some extensions of this idea. First of all it's important to point out that generally when using the `holocube` interfaces you don't explicitly have to supply a list of dimensions as it figures out the key dimensions based on the cube `coords` and value dimension based on the cube value name and unit. You can of course override them but that can become verbose because at least for the kdims you'd also have to manually supply the other dimensions. Simply providing a set of custom dimensions to use may therefore not be sufficient.

In the context of thinking about a general unit system it may therefore be worth considering extending this idea to a truly global registry of dimensions allowing you to control the displayed units and ranges at a global level. This would involve registering dimensions globally, which are applied anywhere a dimension with the same name is used. When fully integrated you could then globally switch between 'Temperature' in Celsius, Kelvin, Fahrenheit, etc., and it would automatically convert between the unit declared on the data dimension and the globally specified unit. Similarly you could globally override the range of a dimension, which is probably what we'd focus on initially.

Edit: There is also a more limited way we could make control over the dimensions more global until we decide on how to handle it in HoloViews. We could simply provide a list of preset dimensions in holocube for now, which the interface looks at when initializing a HoloCube.

**Comment by jlstevens** [comment]
The suggestion you propose in the edit seems sensible and is along the lines of what I consider feasible to implement within a shorter timeframe. The other suggestions are also definitely worth considering but would take more effort to implement.

**Comment by marqh** [comment]
there is a fair bit of units of measure code in iris and scitools

we pushed out some code into a separate module:
https://github.com/SciTools/cf_units

if we want units from a cube

```
cube.units
```

returns a cf_units instance which can return a string representation

I'm not convinced there is more that we need

Iris support convert_units, recalculating data values.  There are already nasty edge cases, kelvin and celsius being the prime example

293 Kelvin = 20 Celsius

293 Kelvin - 273 Kelvin = 20 Kelvin = 20 Celsius

is 20Celsius 20Kelvin or 293Kelvin

caution is required

**Comment by jlstevens** [comment]
@marqh Thanks for pointing us to the relevant unit code!

Perhaps this issue should be split into two parts, one part discussing convenient dimension definitions and one part discussing units (which would involve a lot more work). The two issues are related as `Dimension` objects are currently where we hold unit information.

My understanding is that a lot of names people will be using when dealing with Iris cubes are expected to be standardized. How about an approach that looks like this?
- A preset library of dimensions using standardized names and predefined unit strings. Ranges are also specified when applicable.
- Some means for a user to use these preset `Dimensions` but also customize instances of them. For instance, a dimension representing air pressure might just need an upper bound on the range for normalization purposes.

I feel that something like this could work well for the general case but also make it easy to customize when defining the normalization ranges for specific cubes.

**Comment by marqh** [comment]
closed by #58
